/*
 * Aryeo
 *
 * Contact: jarrod@aryeo.com
 */

/// Order : A payment request for some content or service.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Order {
    /// ID of the order. UUID Version 4.
    #[serde(rename = "id")]
    pub id: String,
    /// A vanity id used for internal tracking of orders for a given vendor.
    #[serde(rename = "number")]
    pub number: i32,
    /// The title of the order, generated by combining the order's number property with the prefix \"Order #\".
    #[serde(rename = "title")]
    pub title: String,
    /// The fulfillment status of the order.
    #[serde(rename = "fulfillment_status")]
    pub fulfillment_status: FulfillmentStatus,
    /// The payment status of the order.
    #[serde(rename = "payment_status")]
    pub payment_status: PaymentStatus,
    /// The three-letter ISO 4217 currency code for the currency in which this order was or will be transacted. Must be a supported currency of Aryeo.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Currency>,
    /// A positive integer in the smallest currency unit (that is, 100 cents for $1.00) representing the total order amount that was or will be charged. This accounts for order items and taxes. 
    #[serde(rename = "total_amount", skip_serializing_if = "Option::is_none")]
    pub total_amount: Option<i32>,
    /// A URL of a publicly-accessible webpage to pay for the order.
    #[serde(rename = "payment_url", skip_serializing_if = "Option::is_none")]
    pub payment_url: Option<String>,
    /// A URL of a publicly-accessible webpage to see the order's status.
    #[serde(rename = "status_url")]
    pub status_url: Option<String>,
    /// Indicates if the current user is allowed to download content from the attached listing.
    #[serde(rename = "downloads_allowed", skip_serializing_if = "Option::is_none")]
    pub downloads_allowed: Option<bool>,
    /// Indicates if the current user is allowed to make a payment for the order.
    #[serde(rename = "payments_allowed", skip_serializing_if = "Option::is_none")]
    pub payments_allowed: Option<bool>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<crate::models::Address>>,
    #[serde(rename = "customer", skip_serializing_if = "Option::is_none")]
    pub customer: Option<Box<crate::models::Group>>,
    #[serde(rename = "listing", skip_serializing_if = "Option::is_none")]
    pub listing: Option<Box<crate::models::Listing>>,
    /// items
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::OrderItem>>,
    #[serde(rename = "appointments", skip_serializing_if = "Option::is_none")]
    pub appointments: Option<Vec<crate::models::Appointment>>,
    #[serde(rename = "unconfirmed_appointments", skip_serializing_if = "Option::is_none")]
    pub unconfirmed_appointments: Option<Vec<crate::models::UnconfirmedAppointment>>,
}

impl Order {
    /// A payment request for some content or service.
    pub fn new(id: String, number: i32, title: String, fulfillment_status: FulfillmentStatus, payment_status: PaymentStatus, status_url: Option<String>) -> Order {
        Order {
            id,
            number,
            title,
            fulfillment_status,
            payment_status,
            currency: None,
            total_amount: None,
            payment_url: None,
            status_url,
            downloads_allowed: None,
            payments_allowed: None,
            address: None,
            customer: None,
            listing: None,
            items: None,
            appointments: None,
            unconfirmed_appointments: None,
        }
    }
}

/// The fulfillment status of the order.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FulfillmentStatus {
    #[serde(rename = "FULFILLED")]
    FULFILLED,
    #[serde(rename = "UNFULFILLED")]
    UNFULFILLED,
}
/// The payment status of the order.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentStatus {
    #[serde(rename = "PAID")]
    PAID,
    #[serde(rename = "UNPAID")]
    UNPAID,
}
/// The three-letter ISO 4217 currency code for the currency in which this order was or will be transacted. Must be a supported currency of Aryeo.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "USD")]
    USD,
    #[serde(rename = "CAD")]
    CAD,
    #[serde(rename = "GBP")]
    GBP,
    #[serde(rename = "CHF")]
    CHF,
    #[serde(rename = "EUR")]
    EUR,
    #[serde(rename = "AUD")]
    AUD,
    #[serde(rename = "NZD")]
    NZD,
    #[serde(rename = "ZAR")]
    ZAR,
}

